services:
    - type: web
      name: gsheet-doc-api
      runtime: python
      buildCommand: pip install -r requirements.txt
      startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
      envVars:
        - key: GOOGLE_CREDS_JSON
          sync: false